# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\aqm_gui_2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 758)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_summary = QtWidgets.QWidget()
        self.tab_summary.setObjectName("tab_summary")
        self.tabWidget.addTab(self.tab_summary, "")
        self.tab_c2c = QtWidgets.QWidget()
        self.tab_c2c.setObjectName("tab_c2c")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_c2c)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget.addTab(self.tab_c2c, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_load.setFont(font)
        self.btn_load.setObjectName("btn_load")
        self.verticalLayout_2.addWidget(self.btn_load)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_start = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_start.setFont(font)
        self.lbl_start.setObjectName("lbl_start")
        self.verticalLayout_3.addWidget(self.lbl_start)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_end = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_end.setFont(font)
        self.lbl_end.setObjectName("lbl_end")
        self.verticalLayout_4.addWidget(self.lbl_end)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_4.addWidget(self.spinBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.list_colors = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_colors.sizePolicy().hasHeightForWidth())
        self.list_colors.setSizePolicy(sizePolicy)
        self.list_colors.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_colors.setFont(font)
        self.list_colors.setObjectName("list_colors")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_colors.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_colors.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_colors.addItem(item)
        self.verticalLayout_2.addWidget(self.list_colors)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.list_panels = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_panels.sizePolicy().hasHeightForWidth())
        self.list_panels.setSizePolicy(sizePolicy)
        self.list_panels.setMaximumSize(QtCore.QSize(200, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_panels.setFont(font)
        self.list_panels.setObjectName("list_panels")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        self.verticalLayout_2.addWidget(self.list_panels)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.list_sets = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_sets.sizePolicy().hasHeightForWidth())
        self.list_sets.setSizePolicy(sizePolicy)
        self.list_sets.setMaximumSize(QtCore.QSize(200, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_sets.setFont(font)
        self.list_sets.setObjectName("list_sets")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        self.verticalLayout_2.addWidget(self.list_sets)
        self.btn_real_start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_real_start.setFont(font)
        self.btn_real_start.setObjectName("btn_real_start")
        self.verticalLayout_2.addWidget(self.btn_real_start)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_summary), _translate("MainWindow", "Summary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_c2c), _translate("MainWindow", "C2C Per Panel"))
        self.btn_load.setText(_translate("MainWindow", "Load Directory"))
        self.lbl_start.setText(_translate("MainWindow", "Start Page"))
        self.lbl_end.setText(_translate("MainWindow", "End Page"))
        self.label.setText(_translate("MainWindow", "Color"))
        __sortingEnabled = self.list_colors.isSortingEnabled()
        self.list_colors.setSortingEnabled(False)
        item = self.list_colors.item(0)
        item.setText(_translate("MainWindow", "Cyan"))
        item = self.list_colors.item(1)
        item.setText(_translate("MainWindow", "Yellow"))
        item = self.list_colors.item(2)
        item.setText(_translate("MainWindow", "Magenta"))
        self.list_colors.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Panel"))
        __sortingEnabled = self.list_panels.isSortingEnabled()
        self.list_panels.setSortingEnabled(False)
        item = self.list_panels.item(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.list_panels.item(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.list_panels.item(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.list_panels.item(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.list_panels.item(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.list_panels.item(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.list_panels.item(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.list_panels.item(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.list_panels.item(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.list_panels.item(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.list_panels.item(10)
        item.setText(_translate("MainWindow", "11"))
        self.list_panels.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Set"))
        __sortingEnabled = self.list_sets.isSortingEnabled()
        self.list_sets.setSortingEnabled(False)
        item = self.list_sets.item(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.list_sets.item(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.list_sets.item(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.list_sets.item(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.list_sets.item(4)
        item.setText(_translate("MainWindow", "5"))
        self.list_sets.setSortingEnabled(__sortingEnabled)
        self.btn_real_start.setText(_translate("MainWindow", "Start Tracking"))
        self.pushButton.setText(_translate("MainWindow", "Stop Tracking"))

