# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\aqm_gui_3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(831, 758)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_load = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load.sizePolicy().hasHeightForWidth())
        self.btn_load.setSizePolicy(sizePolicy)
        self.btn_load.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_load.setFont(font)
        self.btn_load.setCheckable(False)
        self.btn_load.setObjectName("btn_load")
        self.verticalLayout_2.addWidget(self.btn_load)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_start = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_start.sizePolicy().hasHeightForWidth())
        self.lbl_start.setSizePolicy(sizePolicy)
        self.lbl_start.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_start.setFont(font)
        self.lbl_start.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_start.setObjectName("lbl_start")
        self.verticalLayout_3.addWidget(self.lbl_start)
        self.lineEdit_start = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_start.sizePolicy().hasHeightForWidth())
        self.lineEdit_start.setSizePolicy(sizePolicy)
        self.lineEdit_start.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.verticalLayout_3.addWidget(self.lineEdit_start)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.lbl_end = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_end.sizePolicy().hasHeightForWidth())
        self.lbl_end.setSizePolicy(sizePolicy)
        self.lbl_end.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_end.setFont(font)
        self.lbl_end.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_end.setObjectName("lbl_end")
        self.verticalLayout_4.addWidget(self.lbl_end)
        self.lineEdit_end = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_end.sizePolicy().hasHeightForWidth())
        self.lineEdit_end.setSizePolicy(sizePolicy)
        self.lineEdit_end.setMaximumSize(QtCore.QSize(100, 100))
        self.lineEdit_end.setObjectName("lineEdit_end")
        self.verticalLayout_4.addWidget(self.lineEdit_end)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.list_colors = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_colors.sizePolicy().hasHeightForWidth())
        self.list_colors.setSizePolicy(sizePolicy)
        self.list_colors.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_colors.setFont(font)
        self.list_colors.setObjectName("list_colors")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_colors.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_colors.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_colors.addItem(item)
        self.verticalLayout_2.addWidget(self.list_colors)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.list_panels = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_panels.sizePolicy().hasHeightForWidth())
        self.list_panels.setSizePolicy(sizePolicy)
        self.list_panels.setMaximumSize(QtCore.QSize(100, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_panels.setFont(font)
        self.list_panels.setObjectName("list_panels")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_panels.addItem(item)
        self.verticalLayout_2.addWidget(self.list_panels)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.list_sets = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_sets.sizePolicy().hasHeightForWidth())
        self.list_sets.setSizePolicy(sizePolicy)
        self.list_sets.setMaximumSize(QtCore.QSize(100, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.list_sets.setFont(font)
        self.list_sets.setObjectName("list_sets")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.list_sets.addItem(item)
        self.verticalLayout_2.addWidget(self.list_sets)
        self.btn_real_start = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_real_start.sizePolicy().hasHeightForWidth())
        self.btn_real_start.setSizePolicy(sizePolicy)
        self.btn_real_start.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_real_start.setFont(font)
        self.btn_real_start.setObjectName("btn_real_start")
        self.verticalLayout_2.addWidget(self.btn_real_start)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_load.setText(_translate("MainWindow", "Load Directory"))
        self.lbl_start.setText(_translate("MainWindow", "Start Page"))
        self.lbl_end.setText(_translate("MainWindow", "End Page"))
        self.label.setText(_translate("MainWindow", "Color"))
        __sortingEnabled = self.list_colors.isSortingEnabled()
        self.list_colors.setSortingEnabled(False)
        item = self.list_colors.item(0)
        item.setText(_translate("MainWindow", "Cyan"))
        item = self.list_colors.item(1)
        item.setText(_translate("MainWindow", "Yellow"))
        item = self.list_colors.item(2)
        item.setText(_translate("MainWindow", "Magenta"))
        self.list_colors.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Panel"))
        __sortingEnabled = self.list_panels.isSortingEnabled()
        self.list_panels.setSortingEnabled(False)
        item = self.list_panels.item(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.list_panels.item(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.list_panels.item(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.list_panels.item(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.list_panels.item(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.list_panels.item(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.list_panels.item(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.list_panels.item(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.list_panels.item(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.list_panels.item(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.list_panels.item(10)
        item.setText(_translate("MainWindow", "11"))
        self.list_panels.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Set"))
        __sortingEnabled = self.list_sets.isSortingEnabled()
        self.list_sets.setSortingEnabled(False)
        item = self.list_sets.item(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.list_sets.item(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.list_sets.item(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.list_sets.item(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.list_sets.item(4)
        item.setText(_translate("MainWindow", "5"))
        self.list_sets.setSortingEnabled(__sortingEnabled)
        self.btn_real_start.setText(_translate("MainWindow", "Start Tracking"))
        self.pushButton.setText(_translate("MainWindow", "Stop Tracking"))

